In [12]:
### Question 1 

import numpy as np

# Length of a vector
def compute_vector_length(vector):
  len_of_vector = np.linalg.norm(vector)

  return len_of_vector

vector = np.array ([-2, 4, 9, 21])
result = compute_vector_length ([vector])
print(round(result,2))



23.28


In [13]:
# Dot product
def compute_dot_product(vector1, vector2):
  result = np.dot(vector1, vector2)

  return result

v1 = np.array ([0,1,-1,2])
v2 = np.array ([2,5,1,0])
result = compute_dot_product (v1,v2)
print(round(result,2))

4


In [18]:
# Multiplying a vector by a matrix
def matrix_multi_vector(matrix, vector):
  result = np.dot(matrix, vector)
  return result

x = np.array ([[1,2],[3,4]])
k = np.array ([1,2])
print('result1 \n',x.dot (k))

x = np.array ([[ -1 , 2],[3, -4]])
k = np.array ([1 , 2])
print('result2 \n', x@k)

m = np.array ([[-1,1,1], [0,-4,9]])
v = np.array ([0,2,1])
result = matrix_multi_vector(m,v)
print('result3 \n', result)

result 
 [ 5 11]
result 
 [ 3 -5]
result 
 [3 1]


In [22]:
# Multiplying a matrix by a matrix
def matrix_multi_matrix(matrix1, matrix2):
  result = np.dot(matrix1, matrix2)
  return result

m1 = np.array([[0,1,2], [2,-3,1]])
m2 = np.array([[1,-3],[6,1],[0,-1]])
result = matrix_multi_matrix(m1 , m2)
print (result)

m1 = np.eye(3)
m2 = np.array([[1,1,1],[2,2,2], [3,3,3]])
result = m1@m2
print ( result )

m1 = np.eye (2)
m1 = np.reshape (m1,(-1 ,4))[0]
m2 = np.array ([[1,1,1,1] ,[2,2,2,2],[3,3,3,3],[4,4,4,4]])
result = m1@m2
print (result)


m1 = np.array ([[1,2],[3,4]])
m1 = np.reshape(m1,(-1,4) ,"F")[0]
m2 = np.array ([[1,1,1,1] ,[2,2,2,2],[3,3,3,3],[4,4,4,4]])
result = m1@m2
print(result)


[[  6  -1]
 [-16 -10]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
[5. 5. 5. 5.]
[29 29 29 29]


In [23]:
# Matrix inverse
def inverse_matrix(matrix):
  result = np.linalg.inv(matrix)
  return result

m1 = np.array([[-2,6],[8,-4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [24]:
# Question 2 - Eigenvector and Eigenvalue

def compute_eigenvalues_eigenvectors(matrix):
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  return eigenvalues,eigenvectors

matrix = np.array([[0.9,0.2],[0.1,0.8]])
eigenvalues,eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [25]:
# Question 3 - Cosine Similarity

def compute_cosine(v1, v2):
  cos_sim = compute_dot_product(v1,v2) / (compute_vector_length(v1)*compute_vector_length(v2))

  return cos_sim

x = np.array ([1,2,3,4])
y = np.array ([1,0,3,0])
result = compute_cosine(x,y)
print (round(result,3))


0.577
